import type { Module, Mission } from './types';

export const MODULES: Module[] = [
  {
    id: 'm1',
    title: 'Dasar-Dasar Keuangan Pribadi',
    description: 'Pelajari fondasi keuangan pribadi: pengelolaan pendapatan, pengeluaran, dan tabungan.',
    level: 1, minLevel: 1,
    duration: '30 mnt', category: 'keuangan',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=340&fit=crop&auto=format',
    expReward: 100,
  },
  {
    id: 'm2',
    title: 'Mengenal Inflasi & Nilai Uang',
    description: 'Memahami inflasi, deflasi, dan bagaimana nilai uang berubah seiring waktu.',
    level: 1, minLevel: 1,
    duration: '25 mnt', category: 'keuangan',
    thumbnail: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=600&h=340&fit=crop&auto=format',
    expReward: 80,
  },
  {
    id: 'm3',
    title: 'Rekening Bank & Tabungan Cerdas',
    description: 'Strategi menabung efektif dan memilih produk perbankan yang tepat.',
    level: 1, minLevel: 1,
    duration: '20 mnt', category: 'keuangan',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=340&fit=crop&auto=format',
    expReward: 80,
  },
  {
    id: 'm4',
    title: 'Pengenalan Pasar Modal Indonesia',
    description: 'Mengenal Bursa Efek Indonesia, instrumen investasi, dan cara kerja pasar modal.',
    level: 2, minLevel: 2,
    duration: '40 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=340&fit=crop&auto=format',
    expReward: 150,
  },
  {
    id: 'm5',
    title: 'Reksa Dana untuk Pemula',
    description: 'Jenis reksa dana, risiko dan imbal hasil, serta cara memulai investasi reksa dana.',
    level: 2, minLevel: 2,
    duration: '35 mnt', category: 'keuangan',
    thumbnail: 'https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=600&h=340&fit=crop&auto=format',
    expReward: 120,
  },
  {
    id: 'm6',
    title: 'Obligasi & Surat Utang Negara',
    description: 'Memahami obligasi, SBN, ORI, dan cara berinvestasi di instrumen utang.',
    level: 2, minLevel: 2,
    duration: '30 mnt', category: 'keuangan',
    thumbnail: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=600&h=340&fit=crop&auto=format',
    expReward: 120,
  },
  {
    id: 'm7',
    title: 'Analisis Fundamental Saham',
    description: 'Membaca laporan keuangan, memahami rasio keuangan (PE, PBV, ROE), dan valuasi saham.',
    level: 3, minLevel: 3,
    duration: '55 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=600&h=340&fit=crop&auto=format',
    expReward: 200,
  },
  {
    id: 'm8',
    title: 'Analisis Teknikal Dasar',
    description: 'Membaca grafik harga, pola candlestick, support & resistance, dan indikator teknikal.',
    level: 3, minLevel: 3,
    duration: '50 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=340&fit=crop&auto=format',
    expReward: 200,
  },
  {
    id: 'm9',
    title: 'Manajemen Risiko Investasi',
    description: 'Diversifikasi portofolio, stop loss, position sizing, dan strategi mitigasi risiko.',
    level: 3, minLevel: 3,
    duration: '45 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=340&fit=crop&auto=format',
    expReward: 180,
  },
  {
    id: 'm10',
    title: 'Strategi Trading Advanced',
    description: 'Swing trading, momentum investing, dan strategi institusional.',
    level: 4, minLevel: 4,
    duration: '60 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1642543348745-03b1f42b6e4a?w=600&h=340&fit=crop&auto=format',
    expReward: 300,
  },
  {
    id: 'm11',
    title: 'Hedging & Instrumen Derivatif',
    description: 'Opsi saham, futures, dan strategi hedging untuk perlindungan portofolio.',
    level: 4, minLevel: 4,
    duration: '70 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=600&h=340&fit=crop&auto=format',
    expReward: 350,
  },
  {
    id: 'm12',
    title: 'Optimasi Portofolio Modern',
    description: 'Teori portofolio Markowitz, efficient frontier, dan alokasi aset optimal.',
    level: 4, minLevel: 4,
    duration: '65 mnt', category: 'saham',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=340&fit=crop&auto=format',
    expReward: 350,
  },
];

export const QUIZ_QUESTIONS: Record<string, { question: string; options: string[]; answer: number }[]> = {
  m1: [
    { question: 'Apa prinsip utama pengelolaan keuangan pribadi yang sehat?', options: ['Belanjakan semua penghasilan', 'Sisihkan tabungan sebelum belanja', 'Hindari semua investasi', 'Pinjam uang untuk kebutuhan sehari-hari'], answer: 1 },
    { question: 'Berapa persen ideal dari pendapatan yang sebaiknya ditabung?', options: ['5%', '10%', '20%', '50%'], answer: 2 },
    { question: 'Apa yang dimaksud dengan anggaran darurat?', options: ['Dana untuk liburan', 'Dana cadangan 3-6 bulan pengeluaran', 'Dana pensiun', 'Dana investasi'], answer: 1 },
    { question: 'Strategi "Pay Yourself First" berarti...', options: ['Bayar diri sendiri setelah semua tagihan', 'Sisihkan tabungan/investasi SEBELUM belanja lain', 'Investasi hanya saat ada sisa', 'Tidak menabung sama sekali'], answer: 1 },
    { question: 'Apa perbedaan aset dan liabilitas?', options: ['Tidak ada perbedaan', 'Aset = yang dimiliki, Liabilitas = utang/kewajiban', 'Aset = utang, Liabilitas = penghasilan', 'Keduanya adalah penghasilan'], answer: 1 },
  ],
  m2: [
    { question: 'Apa yang dimaksud inflasi?', options: ['Penurunan harga barang', 'Kenaikan harga barang & jasa secara umum', 'Peningkatan nilai tukar', 'Penurunan suku bunga'], answer: 1 },
    { question: 'Jika inflasi 5% per tahun, apa yang terjadi pada daya beli uang Rp1.000.000?', options: ['Naik menjadi Rp1.050.000', 'Tetap sama', 'Turun, hanya bisa beli barang seharga ±Rp952.000', 'Menjadi nol'], answer: 2 },
    { question: 'Instrumen investasi mana yang umumnya bisa mengalahkan inflasi?', options: ['Tabungan biasa', 'Deposito jangka pendek', 'Saham dan reksa dana saham', 'Menyimpan uang tunai'], answer: 2 },
    { question: 'Apa itu deflasi?', options: ['Inflasi yang sangat tinggi', 'Penurunan harga barang & jasa secara umum', 'Kenaikan nilai mata uang', 'Peningkatan suku bunga'], answer: 1 },
    { question: 'Bank Indonesia menggunakan instrumen apa untuk mengendalikan inflasi?', options: ['Mencetak lebih banyak uang', 'Menaikkan/menurunkan suku bunga acuan (BI Rate)', 'Membagikan bantuan tunai', 'Menutup bank swasta'], answer: 1 },
  ],
  m3: [
    { question: 'Apa keunggulan deposito dibanding tabungan biasa?', options: ['Lebih mudah dicairkan', 'Bunga lebih tinggi dengan jangka waktu tertentu', 'Tidak ada bunga', 'Bisa diambil kapan saja'], answer: 1 },
    { question: 'Apa yang dimaksud LPS (Lembaga Penjamin Simpanan)?', options: ['Bank sentral Indonesia', 'Lembaga yang menjamin simpanan nasabah bank hingga batas tertentu', 'Perusahaan asuransi swasta', 'Koperasi simpan pinjam'], answer: 1 },
    { question: 'Berapa batas maksimal simpanan yang dijamin LPS?', options: ['Rp100 juta', 'Rp500 juta', 'Rp2 miliar', 'Tidak ada batas'], answer: 2 },
    { question: 'Strategi menabung yang tepat adalah...', options: ['Menabung sisa dari belanja', 'Otomatis transfer ke rekening tabungan awal bulan', 'Menabung hanya saat ada bonus', 'Tidak perlu menabung jika gaji besar'], answer: 1 },
    { question: 'Apa itu rekening giro?', options: ['Sama persis dengan tabungan biasa', 'Rekening transaksi bisnis dengan fasilitas cek/giro', 'Rekening investasi saham', 'Rekening pensiun'], answer: 1 },
  ],
  m4: [
    { question: 'BEI singkatan dari?', options: ['Bank Ekonomi Indonesia', 'Bursa Efek Indonesia', 'Badan Ekonomi Indonesia', 'Biro Ekspor Indonesia'], answer: 1 },
    { question: 'Apa itu saham?', options: ['Surat utang perusahaan', 'Bukti kepemilikan sebagian perusahaan', 'Rekening tabungan khusus', 'Produk asuransi'], answer: 1 },
    { question: 'Siapa yang mengawasi pasar modal Indonesia?', options: ['Bank Indonesia', 'Kementerian Keuangan', 'OJK (Otoritas Jasa Keuangan)', 'BEI'], answer: 2 },
    { question: 'Apa yang dimaksud lot dalam perdagangan saham di BEI?', options: ['1 lembar saham', '100 lembar saham', '1.000 lembar saham', '10 lembar saham'], answer: 1 },
    { question: 'Apa itu dividen?', options: ['Kerugian investasi', 'Pembagian keuntungan perusahaan kepada pemegang saham', 'Biaya transaksi saham', 'Pajak investasi'], answer: 1 },
  ],
  m5: [
    { question: 'Reksa dana adalah...', options: ['Investasi langsung di saham', 'Wadah menghimpun dana investor yang dikelola manajer investasi', 'Tabungan dengan bunga tinggi', 'Asuransi investasi'], answer: 1 },
    { question: 'Reksa dana manakah yang memiliki risiko paling rendah?', options: ['Reksa Dana Saham', 'Reksa Dana Campuran', 'Reksa Dana Pasar Uang', 'Reksa Dana Indeks'], answer: 2 },
    { question: 'Apa itu NAB (Nilai Aktiva Bersih)?', options: ['Keuntungan reksa dana per tahun', 'Harga per unit penyertaan reksa dana', 'Total aset manajer investasi', 'Biaya pengelolaan dana'], answer: 1 },
    { question: 'Keunggulan reksa dana dibanding investasi langsung di saham bagi pemula adalah...', options: ['Lebih mahal biayanya', 'Dikelola profesional, diversifikasi otomatis', 'Risiko lebih tinggi', 'Harus modal besar'], answer: 1 },
    { question: 'Apa yang dimaksud expense ratio pada reksa dana?', options: ['Keuntungan tahunan investor', 'Biaya pengelolaan yang dibebankan ke reksa dana', 'Pajak penghasilan investor', 'Minimum investasi awal'], answer: 1 },
  ],
  m6: [
    { question: 'ORI singkatan dari?', options: ['Obligasi Ritel Indonesia', 'Opsi Reksadana Indonesia', 'Otoritas Rekening Indonesia', 'Obligasi Rupiah Internasional'], answer: 0 },
    { question: 'Apa perbedaan obligasi korporasi dan obligasi pemerintah?', options: ['Tidak ada perbedaan', 'Obligasi korporasi risikonya lebih tinggi dari pemerintah', 'Obligasi pemerintah risikonya lebih tinggi', 'Keduanya sama-sama bebas risiko'], answer: 1 },
    { question: 'Kupon dalam obligasi adalah...', options: ['Hadiah undian', 'Bunga yang dibayarkan secara berkala kepada pemegang obligasi', 'Potongan harga obligasi', 'Biaya pembelian obligasi'], answer: 1 },
    { question: 'Jika suku bunga naik, harga obligasi cenderung...', options: ['Naik', 'Turun', 'Tetap sama', 'Tidak ada hubungannya'], answer: 1 },
    { question: 'Apa itu yield to maturity (YTM)?', options: ['Harga obligasi saat jatuh tempo', 'Total imbal hasil jika obligasi dipegang hingga jatuh tempo', 'Suku bunga bank sentral', 'Biaya penerbitan obligasi'], answer: 1 },
  ],
  m7: [
    { question: 'Price to Earnings Ratio (PER) dihitung dengan rumus?', options: ['Laba per saham / Harga saham', 'Harga saham / Laba per saham (EPS)', 'Total aset / Harga saham', 'Harga saham × Jumlah saham'], answer: 1 },
    { question: 'ROE (Return on Equity) mengukur...', options: ['Kemampuan aset menghasilkan laba', 'Kemampuan ekuitas (modal) menghasilkan laba', 'Rasio utang perusahaan', 'Pertumbuhan pendapatan'], answer: 1 },
    { question: 'Apa yang dimaksud dengan PBV (Price to Book Value)?', options: ['Perbandingan harga saham dengan nilai buku per saham', 'Total penjualan per saham', 'Dividen per saham', 'Laba bersih per saham'], answer: 0 },
    { question: 'Laporan keuangan yang menunjukkan posisi keuangan perusahaan pada tanggal tertentu adalah...', options: ['Laporan Laba Rugi', 'Neraca (Balance Sheet)', 'Laporan Arus Kas', 'Catatan atas Laporan Keuangan'], answer: 1 },
    { question: 'Current Ratio mengukur...', options: ['Profitabilitas perusahaan', 'Kemampuan membayar kewajiban jangka pendek', 'Pertumbuhan pendapatan', 'Efisiensi operasional'], answer: 1 },
  ],
  m8: [
    { question: 'Pola candlestick "Bullish Engulfing" mengindikasikan...', options: ['Penerusan tren turun', 'Potensi pembalikan tren menjadi naik', 'Tidak ada sinyal', 'Tren sideway'], answer: 1 },
    { question: 'Support level adalah...', options: ['Level harga tertinggi yang pernah dicapai', 'Level harga yang menjadi area pembelian (demand zone)', 'Level harga untuk take profit', 'Garis rata-rata harga'], answer: 1 },
    { question: 'Moving Average digunakan untuk...', options: ['Mengukur volume perdagangan', 'Menghaluskan fluktuasi harga dan mengidentifikasi tren', 'Menghitung dividen saham', 'Mengukur rasio keuangan'], answer: 1 },
    { question: 'RSI (Relative Strength Index) menunjukkan kondisi "Overbought" jika nilai...', options: ['Di bawah 30', 'Di atas 70', 'Tepat di 50', 'Di bawah 20'], answer: 1 },
    { question: 'Apa yang dimaksud Golden Cross dalam analisis teknikal?', options: ['MA jangka pendek memotong MA jangka panjang dari bawah ke atas', 'MA jangka panjang memotong MA jangka pendek ke atas', 'Harga mencapai level tertinggi sepanjang masa', 'Volume perdagangan tinggi'], answer: 0 },
  ],
  m9: [
    { question: 'Diversifikasi portofolio bertujuan untuk...', options: ['Memaksimalkan keuntungan', 'Mengurangi risiko dengan menyebar investasi di berbagai aset', 'Meningkatkan risiko agar imbal hasil lebih tinggi', 'Fokus pada satu saham terbaik'], answer: 1 },
    { question: 'Stop loss adalah strategi...', options: ['Otomatis menjual saham jika harga turun ke level tertentu untuk membatasi kerugian', 'Membeli lebih banyak saham saat harga turun', 'Menyimpan saham tanpa batas waktu', 'Mengambil keuntungan saat harga naik'], answer: 0 },
    { question: 'Apa yang dimaksud dengan korelasi dalam konteks portofolio?', options: ['Ukuran profitabilitas saham', 'Seberapa kuat hubungan pergerakan harga antar aset', 'Rasio utang perusahaan', 'Volume perdagangan harian'], answer: 1 },
    { question: 'Manfaat memiliki aset dengan korelasi negatif dalam portofolio adalah...', options: ['Meningkatkan volatilitas keseluruhan', 'Jika satu aset turun, yang lain cenderung naik, mengurangi risiko total', 'Mengurangi potensi keuntungan secara signifikan', 'Tidak ada manfaatnya'], answer: 1 },
    { question: 'Apa yang dimaksud position sizing?', options: ['Ukuran layar monitor trader', 'Menentukan berapa banyak modal yang dialokasikan untuk satu posisi', 'Jumlah saham yang diperdagangkan di bursa', 'Durasi investasi'], answer: 1 },
  ],
  m10: [
    { question: 'Swing trading berfokus pada...', options: ['Perdagangan dalam hitungan detik', 'Menangkap pergerakan harga dalam beberapa hari hingga minggu', 'Investasi jangka panjang 10 tahun', 'Hanya membeli saham dividen'], answer: 1 },
    { question: 'Apa itu momentum investing?', options: ['Membeli saham yang sedang turun tajam', 'Membeli aset yang menunjukkan tren kuat dan momentum positif', 'Strategi investasi value investing', 'Berinvestasi tanpa analisis'], answer: 1 },
    { question: 'Fibonacci retracement digunakan untuk...', options: ['Menghitung laba perusahaan', 'Mengidentifikasi level support dan resistance potensial', 'Mengukur volatilitas pasar', 'Menentukan waktu pembagian dividen'], answer: 1 },
    { question: 'Apa yang dimaksud dengan Volume Profile?', options: ['Profil media sosial trader', 'Distribusi volume perdagangan pada level harga tertentu', 'Jumlah saham yang beredar', 'Laporan keuangan tahunan'], answer: 1 },
    { question: 'VWAP (Volume Weighted Average Price) sering digunakan sebagai...', options: ['Indikator sentimen pasar jangka panjang', 'Acuan harga rata-rata intraday yang digunakan institusi', 'Alat untuk menghitung dividen', 'Pengukur volatilitas bulanan'], answer: 1 },
  ],
  m11: [
    { question: 'Apa tujuan utama hedging?', options: ['Memaksimalkan keuntungan', 'Melindungi posisi investasi dari risiko kerugian', 'Meningkatkan leverage', 'Menghindari pajak'], answer: 1 },
    { question: 'Opsi "Call" memberikan hak kepada pemegangnya untuk...', options: ['Menjual aset dengan harga tertentu', 'Membeli aset dengan harga tertentu (strike price)', 'Meminjam aset dari broker', 'Mendapatkan dividen lebih besar'], answer: 1 },
    { question: 'Apa itu kontrak futures?', options: ['Perjanjian untuk membeli/menjual aset di masa depan dengan harga yang disepakati sekarang', 'Opsi yang kedaluwarsa besok', 'Reksa dana dengan jangka waktu tertentu', 'Obligasi jangka pendek'], answer: 0 },
    { question: 'Delta dalam opsi mengukur...', options: ['Waktu hingga kedaluwarsa', 'Sensitivitas harga opsi terhadap perubahan harga aset acuan', 'Tingkat volatilitas aset', 'Suku bunga bebas risiko'], answer: 1 },
    { question: 'Strategi "Covered Call" melibatkan...', options: ['Membeli call option tanpa memiliki saham', 'Menjual call option atas saham yang sudah dimiliki', 'Membeli put dan call option sekaligus', 'Short selling saham'], answer: 1 },
  ],
  m12: [
    { question: 'Apa yang dimaksud Efficient Frontier dalam teori Markowitz?', options: ['Batas maksimum keuntungan pasar', 'Kumpulan portofolio optimal yang memberikan return maksimal untuk setiap level risiko', 'Biaya transaksi tertinggi yang diizinkan', 'Regulasi pasar modal'], answer: 1 },
    { question: 'Sharpe Ratio mengukur...', options: ['Risiko total portofolio', 'Imbal hasil berlebih per unit risiko (risk-adjusted return)', 'Korelasi antar aset', 'Biaya pengelolaan dana'], answer: 1 },
    { question: 'Apa itu rebalancing portofolio?', options: ['Menghapus semua posisi yang rugi', 'Menyesuaikan kembali alokasi aset ke target semula secara berkala', 'Mengubah strategi investasi total', 'Menjual semua aset saat pasar turun'], answer: 1 },
    { question: 'Beta portofolio mengukur...', options: ['Imbal hasil absolut', 'Sensitivitas portofolio terhadap pergerakan pasar keseluruhan', 'Dividen yang dibayarkan', 'Biaya transaksi'], answer: 1 },
    { question: 'Alokasi aset antara saham dan obligasi yang disarankan untuk investor konservatif adalah...', options: ['90% saham, 10% obligasi', '60% saham, 40% obligasi', '30% saham, 70% obligasi', '100% saham'], answer: 2 },
  ],
};

export const MISSIONS: Mission[] = [
  { id: 'dm1', title: 'Selesaikan 1 Modul', description: 'Tuntaskan satu modul materi hari ini', type: 'daily', expReward: 50, target: 1, progress: 0, completed: false, icon: '📚' },
  { id: 'dm2', title: 'Login Beruntun', description: 'Login ke aplikasi hari ini', type: 'daily', expReward: 20, target: 1, progress: 0, completed: false, icon: '🔥' },
  { id: 'dm3', title: 'Tanya AI Assistant', description: 'Ajukan 3 pertanyaan ke AI Assistant', type: 'daily', expReward: 30, target: 3, progress: 0, completed: false, icon: '🤖' },
  { id: 'dm4', title: 'Coba Challenge', description: 'Akses fitur Challenge hari ini', type: 'daily', expReward: 25, target: 1, progress: 0, completed: false, icon: '⚡' },
  { id: 'wm1', title: 'Selesaikan 5 Modul', description: 'Tuntaskan 5 modul dalam minggu ini', type: 'weekly', expReward: 300, target: 5, progress: 0, completed: false, icon: '🎯' },
  { id: 'wm2', title: 'Streak 7 Hari', description: 'Pertahankan streak login 7 hari berturut-turut', type: 'weekly', expReward: 200, target: 7, progress: 0, completed: false, icon: '🏆' },
  { id: 'wm3', title: 'Simulasi Portofolio', description: 'Jalankan simulasi portofolio 3 kali minggu ini', type: 'weekly', expReward: 250, target: 3, progress: 0, completed: false, icon: '💼' },
  { id: 'wm4', title: 'Skor Quiz Sempurna', description: 'Raih nilai 100% pada 2 quiz dalam minggu ini', type: 'weekly', expReward: 400, target: 2, progress: 0, completed: false, icon: '⭐' },
];

export const PLACEMENT_QUESTIONS = [
  {
    question: 'Apa yang dimaksud dengan inflasi dalam ekonomi?',
    options: ['Penurunan nilai mata uang asing', 'Kenaikan harga barang & jasa secara umum dan terus-menerus', 'Peningkatan jumlah lapangan kerja', 'Kenaikan nilai ekspor suatu negara'],
    answer: 1,
  },
  {
    question: 'Apa itu PE Ratio (Price to Earnings Ratio)?',
    options: ['Perbandingan harga saham terhadap laba per saham', 'Perbandingan pendapatan terhadap pengeluaran', 'Tingkat bunga pinjaman bank', 'Rasio utang terhadap ekuitas'],
    answer: 0,
  },
  {
    question: 'Diversifikasi dalam investasi berarti...',
    options: ['Menginvestasikan semua uang pada satu instrumen terbaik', 'Menyebar investasi ke berbagai instrumen untuk mengurangi risiko', 'Berinvestasi hanya di pasar saham', 'Menabung di berbagai bank'],
    answer: 1,
  },
  {
    question: 'Apa perbedaan antara saham dan obligasi?',
    options: ['Keduanya adalah bentuk tabungan bank', 'Saham = kepemilikan perusahaan; Obligasi = surat utang dengan bunga tetap', 'Saham lebih aman dari obligasi', 'Obligasi memberikan keuntungan lebih tinggi dari saham'],
    answer: 1,
  },
  {
    question: 'Apa yang dimaksud dengan reksa dana?',
    options: ['Investasi langsung di pasar saham tanpa perantara', 'Wadah investasi kolektif yang dikelola oleh manajer investasi profesional', 'Tabungan berjangka di bank', 'Asuransi jiwa'],
    answer: 1,
  },
  {
    question: 'Manakah indikator teknikal yang umum digunakan untuk mengidentifikasi tren?',
    options: ['PER dan PBV', 'Current Ratio dan Quick Ratio', 'Moving Average dan RSI', 'ROE dan ROA'],
    answer: 2,
  },
  {
    question: 'Apa yang dimaksud dengan likuiditas dalam konteks investasi?',
    options: ['Tingkat keuntungan suatu investasi', 'Kemudahan suatu aset untuk dikonversi menjadi uang tunai', 'Besarnya modal yang diinvestasikan', 'Jangka waktu investasi'],
    answer: 1,
  },
];

